name: k6 LOGIN test

on:
  repository_dispatch:
  name: cars test

jobs:
  k6_local_login_test:
    name: k6 local test on macos
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install k6 by homebrew
        run: brew install k6

      - name: Install Node.js dependencies
        run: npm install

      - name: k6 LOGIN test
        run: k6 run ./test/carsTest.js

      - name: Publish HTML report
          uses: actions/uplead-artifact@v1
          if: always()
          with:
            name: K6 cars test
            path: reports/CARS.html
