name: K6 LOGIN performance test

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'K6 performance test'
        required: true
        default: 'test'

jobs:
  k6_local_login_test:
    name: k6 local test on macos
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install k6 by homebrew
        run: brew install k6

      - name: Local k6 LOGIN test
        run: k6 run ./k6/test/loginTest.js
