name: k6 performance test

on:
  workflow_dispatch:
    #ref: refs/heads/main
    inputs:
      test:
        type: choice
        description: test name
        required: true
        options:
          - 'loginTest'
          - 'carsTest'
      users:
        type: choice
        description: virtual users
        required: true
        options:
          - '1'
          - '10'
          - '100'
      environment:
        type: choice
        description: test environment
        required: true
        options:
          - 'staging'
          - 'production'
jobs:
  performance_test:
    name: Performance ${{ github.event.inputs.test }} [${{ github.event.inputs.users }} users] [${{ github.event.inputs.environment }}]
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install k6 by homebrew
        run: brew install k6

      - name: k6 ${{ github.event.inputs.test }}
        env:
          environment: ${{ github.event.inputs.environment }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
        run: |
          echo "Running k6 performance tests against: ${{ github.event.inputs.environment }}"
          k6 run ./test/${{ github.event.inputs.test }}.js -u ${{ github.event.inputs.users }} -i ${{ github.event.inputs.users }}

      - name: Publish HTML report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: ${{ github.event.inputs.test }}.performace.${{ github.event.inputs.users }}.${{ github.event.inputs.environment }}.report
          path: reports/${{ github.event.inputs.test }}.html
